import simple_sg.parse

from troposphere import Output, Ref, Template


template = Template(
    Description='CloudFormation Template for dynamic Security Groups (generated by Troposphere)'
)

security_groups = simple_sg.parse.parse_yaml('example.yml')

for sg_definition in security_groups:
    sg = simple_sg.parse.create_sg(**sg_definition)
    sg_output = Output(
        sg_definition['id'],
        Description=sg_definition['description'],
        Value=Ref(sg))

    template.add_resource(sg)
    template.add_output(sg_output)

    rules = simple_sg.parse.create_sg_ingress_rules(
        sg,
        sg_definition['rules']['ingress']
    )

    template.add_resource(rules)

print(template.to_yaml())